export const Strings = {
  app_name: 'PeachSpend',
  outlineVariant:           '#53433F',
  success:                  '#81C784',
  error:                    '#FF8A80',
  // Convenience aliases
  onboarding: {
    slide1_title: 'Track Beautifully',
    slide1_subtitle: 'Experience expense tracking with a premium, luminous touch.',
    slide2_title: 'Scan in Seconds',
    slide2_subtitle: 'Let Gemini AI handle the data entry from your receipts.',
    slide3_title: 'Know Your Spending',
    slide3_subtitle: 'Get deep insights into your financial habits instantly.',
    get_started: 'Get Started',
  },
  home: {
    greeting_morning: 'Good Morning',
    greeting_afternoon: 'Good Afternoon',
    greeting_evening: 'Good Evening',
    spending_this_month: 'Spending this month',
    total_spending: 'Total Spending',
    manual_entry: 'Manual Entry',
    recent_expenses: 'Recent Activity',
    add_funds: 'Manual Entry',
    no_expenses: 'Your financial ledger is empty. Scan a receipt to begin.',
  },
  review: {
    title: 'Review Details',
    subtitle: 'Ensure your spending is recorded accurately.',
    merchant: 'Merchant',
    amount: 'Amount',
    category: 'Category',
    save: 'Save Expense',
  },
  settings: {
    title: 'Settings',
    profile: 'Profile',
    security: 'Biometrics',
    ai_preferences: 'Intelligence',
    gemini_api_key: 'Gemini 2.5 API Key',
    smart_scan: 'Neural Scan',
    smart_insights: 'Predictive Insights',
    currency: 'Currency',
    appearance: 'Appearance',
    clear_data: 'Purge All Data',
  },
  scan: {
    title: 'Neural Scan',
    camera_permission: 'We need your vision to process receipts.',
    grant_permission: 'Grant Access',
    processing: 'Gemini is reading...',
  },
  analytics: {
    title: 'Flow Insights',
    subtitle: 'Track your spending movement.',
  },
} as const;
